/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsClaudeCodeIndexRouteImport } from './routes/tools/claude-code/index'
import { Route as ToolsClaudeCodeReleasesVersionRouteImport } from './routes/tools/claude-code/releases/$version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsClaudeCodeIndexRoute = ToolsClaudeCodeIndexRouteImport.update({
  id: '/tools/claude-code/',
  path: '/tools/claude-code/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsClaudeCodeReleasesVersionRoute =
  ToolsClaudeCodeReleasesVersionRouteImport.update({
    id: '/tools/claude-code/releases/$version',
    path: '/tools/claude-code/releases/$version',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/claude-code': typeof ToolsClaudeCodeIndexRoute
  '/tools/claude-code/releases/$version': typeof ToolsClaudeCodeReleasesVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/claude-code': typeof ToolsClaudeCodeIndexRoute
  '/tools/claude-code/releases/$version': typeof ToolsClaudeCodeReleasesVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/claude-code/': typeof ToolsClaudeCodeIndexRoute
  '/tools/claude-code/releases/$version': typeof ToolsClaudeCodeReleasesVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/claude-code' | '/tools/claude-code/releases/$version'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools/claude-code' | '/tools/claude-code/releases/$version'
  id:
    | '__root__'
    | '/'
    | '/tools/claude-code/'
    | '/tools/claude-code/releases/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsClaudeCodeIndexRoute: typeof ToolsClaudeCodeIndexRoute
  ToolsClaudeCodeReleasesVersionRoute: typeof ToolsClaudeCodeReleasesVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/claude-code/': {
      id: '/tools/claude-code/'
      path: '/tools/claude-code'
      fullPath: '/tools/claude-code'
      preLoaderRoute: typeof ToolsClaudeCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/claude-code/releases/$version': {
      id: '/tools/claude-code/releases/$version'
      path: '/tools/claude-code/releases/$version'
      fullPath: '/tools/claude-code/releases/$version'
      preLoaderRoute: typeof ToolsClaudeCodeReleasesVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsClaudeCodeIndexRoute: ToolsClaudeCodeIndexRoute,
  ToolsClaudeCodeReleasesVersionRoute: ToolsClaudeCodeReleasesVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
