/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as ToolsSlugIndexRouteImport } from './routes/tools/$slug/index'
import { Route as ToolsSlugReleasesVersionRouteImport } from './routes/tools/$slug/releases/$version'

const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugIndexRoute = ToolsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsSlugRoute,
} as any)
const ToolsSlugReleasesVersionRoute =
  ToolsSlugReleasesVersionRouteImport.update({
    id: '/releases/$version',
    path: '/releases/$version',
    getParentRoute: () => ToolsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRouteWithChildren
  '/analytics/': typeof AnalyticsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/$slug/': typeof ToolsSlugIndexRoute
  '/tools/$slug/releases/$version': typeof ToolsSlugReleasesVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/$slug': typeof ToolsSlugIndexRoute
  '/tools/$slug/releases/$version': typeof ToolsSlugReleasesVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRouteWithChildren
  '/analytics/': typeof AnalyticsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$slug/': typeof ToolsSlugIndexRoute
  '/tools/$slug/releases/$version': typeof ToolsSlugReleasesVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/tools/$slug'
    | '/analytics/'
    | '/tools'
    | '/tools/$slug/'
    | '/tools/$slug/releases/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/tools'
    | '/tools/$slug'
    | '/tools/$slug/releases/$version'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/tools/$slug'
    | '/analytics/'
    | '/tools/'
    | '/tools/$slug/'
    | '/tools/$slug/releases/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  ToolsSlugRoute: typeof ToolsSlugRouteWithChildren
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug/': {
      id: '/tools/$slug/'
      path: '/'
      fullPath: '/tools/$slug/'
      preLoaderRoute: typeof ToolsSlugIndexRouteImport
      parentRoute: typeof ToolsSlugRoute
    }
    '/tools/$slug/releases/$version': {
      id: '/tools/$slug/releases/$version'
      path: '/releases/$version'
      fullPath: '/tools/$slug/releases/$version'
      preLoaderRoute: typeof ToolsSlugReleasesVersionRouteImport
      parentRoute: typeof ToolsSlugRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface ToolsSlugRouteChildren {
  ToolsSlugIndexRoute: typeof ToolsSlugIndexRoute
  ToolsSlugReleasesVersionRoute: typeof ToolsSlugReleasesVersionRoute
}

const ToolsSlugRouteChildren: ToolsSlugRouteChildren = {
  ToolsSlugIndexRoute: ToolsSlugIndexRoute,
  ToolsSlugReleasesVersionRoute: ToolsSlugReleasesVersionRoute,
}

const ToolsSlugRouteWithChildren = ToolsSlugRoute._addFileChildren(
  ToolsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  ToolsSlugRoute: ToolsSlugRouteWithChildren,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
