/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as OgIndexRouteImport } from './routes/og/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as OgToolsRouteImport } from './routes/og/tools'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as AdminToolsRouteImport } from './routes/admin/tools'
import { Route as AdminTestEmailRouteImport } from './routes/admin/test-email'
import { Route as AdminIngestionRouteImport } from './routes/admin/ingestion'
import { Route as AdminEmailsRouteImport } from './routes/admin/emails'
import { Route as AdminDigestsRouteImport } from './routes/admin/digests'
import { Route as AdminBroadcastRouteImport } from './routes/admin/broadcast'
import { Route as ToolsSlugIndexRouteImport } from './routes/tools/$slug/index'
import { Route as OgToolsSlugRouteImport } from './routes/og/tools.$slug'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminToolsSlugRouteImport } from './routes/admin/tools_.$slug'
import { Route as ToolsSlugReleasesVersionRouteImport } from './routes/tools/$slug/releases/$version'
import { Route as OgToolsSlugReleasesVersionRouteImport } from './routes/og/tools.$slug.releases.$version'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgIndexRoute = OgIndexRouteImport.update({
  id: '/og/',
  path: '/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgToolsRoute = OgToolsRouteImport.update({
  id: '/og/tools',
  path: '/og/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestEmailRoute = AdminTestEmailRouteImport.update({
  id: '/test-email',
  path: '/test-email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngestionRoute = AdminIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDigestsRoute = AdminDigestsRouteImport.update({
  id: '/digests',
  path: '/digests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsSlugIndexRoute = ToolsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsSlugRoute,
} as any)
const OgToolsSlugRoute = OgToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OgToolsRoute,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsSlugRoute = AdminToolsSlugRouteImport.update({
  id: '/tools_/$slug',
  path: '/tools/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsSlugReleasesVersionRoute =
  ToolsSlugReleasesVersionRouteImport.update({
    id: '/releases/$version',
    path: '/releases/$version',
    getParentRoute: () => ToolsSlugRoute,
  } as any)
const OgToolsSlugReleasesVersionRoute =
  OgToolsSlugReleasesVersionRouteImport.update({
    id: '/releases/$version',
    path: '/releases/$version',
    getParentRoute: () => OgToolsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/digests': typeof AdminDigestsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/test-email': typeof AdminTestEmailRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/og/tools': typeof OgToolsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/og': typeof OgIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/tools/$slug': typeof AdminToolsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/og/tools/$slug': typeof OgToolsSlugRouteWithChildren
  '/tools/$slug/': typeof ToolsSlugIndexRoute
  '/tools/$slug/releases/$version': typeof ToolsSlugReleasesVersionRoute
  '/og/tools/$slug/releases/$version': typeof OgToolsSlugReleasesVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/digests': typeof AdminDigestsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/test-email': typeof AdminTestEmailRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/og/tools': typeof OgToolsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/og': typeof OgIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/tools/$slug': typeof AdminToolsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/og/tools/$slug': typeof OgToolsSlugRouteWithChildren
  '/tools/$slug': typeof ToolsSlugIndexRoute
  '/tools/$slug/releases/$version': typeof ToolsSlugReleasesVersionRoute
  '/og/tools/$slug/releases/$version': typeof OgToolsSlugReleasesVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/digests': typeof AdminDigestsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/test-email': typeof AdminTestEmailRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/og/tools': typeof OgToolsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/og/': typeof OgIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/tools_/$slug': typeof AdminToolsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/og/tools/$slug': typeof OgToolsSlugRouteWithChildren
  '/tools/$slug/': typeof ToolsSlugIndexRoute
  '/tools/$slug/releases/$version': typeof ToolsSlugReleasesVersionRoute
  '/og/tools/$slug/releases/$version': typeof OgToolsSlugReleasesVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/changelog'
    | '/compare'
    | '/login'
    | '/unsubscribe'
    | '/admin/broadcast'
    | '/admin/digests'
    | '/admin/emails'
    | '/admin/ingestion'
    | '/admin/test-email'
    | '/admin/tools'
    | '/api/unsubscribe'
    | '/og/tools'
    | '/tools/$slug'
    | '/admin/'
    | '/og'
    | '/tools'
    | '/admin/tools/$slug'
    | '/api/auth/$'
    | '/api/webhooks/resend'
    | '/og/tools/$slug'
    | '/tools/$slug/'
    | '/tools/$slug/releases/$version'
    | '/og/tools/$slug/releases/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/changelog'
    | '/compare'
    | '/login'
    | '/unsubscribe'
    | '/admin/broadcast'
    | '/admin/digests'
    | '/admin/emails'
    | '/admin/ingestion'
    | '/admin/test-email'
    | '/admin/tools'
    | '/api/unsubscribe'
    | '/og/tools'
    | '/admin'
    | '/og'
    | '/tools'
    | '/admin/tools/$slug'
    | '/api/auth/$'
    | '/api/webhooks/resend'
    | '/og/tools/$slug'
    | '/tools/$slug'
    | '/tools/$slug/releases/$version'
    | '/og/tools/$slug/releases/$version'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/changelog'
    | '/compare'
    | '/login'
    | '/unsubscribe'
    | '/admin/broadcast'
    | '/admin/digests'
    | '/admin/emails'
    | '/admin/ingestion'
    | '/admin/test-email'
    | '/admin/tools'
    | '/api/unsubscribe'
    | '/og/tools'
    | '/tools/$slug'
    | '/admin/'
    | '/og/'
    | '/tools/'
    | '/admin/tools_/$slug'
    | '/api/auth/$'
    | '/api/webhooks/resend'
    | '/og/tools/$slug'
    | '/tools/$slug/'
    | '/tools/$slug/releases/$version'
    | '/og/tools/$slug/releases/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ChangelogRoute: typeof ChangelogRoute
  CompareRoute: typeof CompareRoute
  LoginRoute: typeof LoginRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
  OgToolsRoute: typeof OgToolsRouteWithChildren
  ToolsSlugRoute: typeof ToolsSlugRouteWithChildren
  OgIndexRoute: typeof OgIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/': {
      id: '/og/'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/tools': {
      id: '/og/tools'
      path: '/og/tools'
      fullPath: '/og/tools'
      preLoaderRoute: typeof OgToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-email': {
      id: '/admin/test-email'
      path: '/test-email'
      fullPath: '/admin/test-email'
      preLoaderRoute: typeof AdminTestEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingestion': {
      id: '/admin/ingestion'
      path: '/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminIngestionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/digests': {
      id: '/admin/digests'
      path: '/digests'
      fullPath: '/admin/digests'
      preLoaderRoute: typeof AdminDigestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/$slug/': {
      id: '/tools/$slug/'
      path: '/'
      fullPath: '/tools/$slug/'
      preLoaderRoute: typeof ToolsSlugIndexRouteImport
      parentRoute: typeof ToolsSlugRoute
    }
    '/og/tools/$slug': {
      id: '/og/tools/$slug'
      path: '/$slug'
      fullPath: '/og/tools/$slug'
      preLoaderRoute: typeof OgToolsSlugRouteImport
      parentRoute: typeof OgToolsRoute
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools_/$slug': {
      id: '/admin/tools_/$slug'
      path: '/tools/$slug'
      fullPath: '/admin/tools/$slug'
      preLoaderRoute: typeof AdminToolsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/$slug/releases/$version': {
      id: '/tools/$slug/releases/$version'
      path: '/releases/$version'
      fullPath: '/tools/$slug/releases/$version'
      preLoaderRoute: typeof ToolsSlugReleasesVersionRouteImport
      parentRoute: typeof ToolsSlugRoute
    }
    '/og/tools/$slug/releases/$version': {
      id: '/og/tools/$slug/releases/$version'
      path: '/releases/$version'
      fullPath: '/og/tools/$slug/releases/$version'
      preLoaderRoute: typeof OgToolsSlugReleasesVersionRouteImport
      parentRoute: typeof OgToolsSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminDigestsRoute: typeof AdminDigestsRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminIngestionRoute: typeof AdminIngestionRoute
  AdminTestEmailRoute: typeof AdminTestEmailRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminToolsSlugRoute: typeof AdminToolsSlugRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminDigestsRoute: AdminDigestsRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminIngestionRoute: AdminIngestionRoute,
  AdminTestEmailRoute: AdminTestEmailRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminToolsSlugRoute: AdminToolsSlugRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OgToolsSlugRouteChildren {
  OgToolsSlugReleasesVersionRoute: typeof OgToolsSlugReleasesVersionRoute
}

const OgToolsSlugRouteChildren: OgToolsSlugRouteChildren = {
  OgToolsSlugReleasesVersionRoute: OgToolsSlugReleasesVersionRoute,
}

const OgToolsSlugRouteWithChildren = OgToolsSlugRoute._addFileChildren(
  OgToolsSlugRouteChildren,
)

interface OgToolsRouteChildren {
  OgToolsSlugRoute: typeof OgToolsSlugRouteWithChildren
}

const OgToolsRouteChildren: OgToolsRouteChildren = {
  OgToolsSlugRoute: OgToolsSlugRouteWithChildren,
}

const OgToolsRouteWithChildren =
  OgToolsRoute._addFileChildren(OgToolsRouteChildren)

interface ToolsSlugRouteChildren {
  ToolsSlugIndexRoute: typeof ToolsSlugIndexRoute
  ToolsSlugReleasesVersionRoute: typeof ToolsSlugReleasesVersionRoute
}

const ToolsSlugRouteChildren: ToolsSlugRouteChildren = {
  ToolsSlugIndexRoute: ToolsSlugIndexRoute,
  ToolsSlugReleasesVersionRoute: ToolsSlugReleasesVersionRoute,
}

const ToolsSlugRouteWithChildren = ToolsSlugRoute._addFileChildren(
  ToolsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ChangelogRoute: ChangelogRoute,
  CompareRoute: CompareRoute,
  LoginRoute: LoginRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
  OgToolsRoute: OgToolsRouteWithChildren,
  ToolsSlugRoute: ToolsSlugRouteWithChildren,
  OgIndexRoute: OgIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
